"""
Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


Answer:
4613732
Completed on Thu, 15 Sep 2016, 22:09

"""

def main():

	fib_list = [1,2]
	i = 1
	x = True
	while True:
		fib_list.append(fib_list[i]+fib_list[i-1])
		if fib_list[-1] >= 4000000:
			break
		else:
			i= i+1
	even_list_sum = sum([item for item in fib_list if item % 2 == 0])
	print even_list_sum

if __name__ == "__main__":
	main()
